// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACUc7ZO7-TlP-JPY-GmqUQmR3ZCkUOues',
    appId: '1:117976496895:web:515eef611b0218ad96aaca',
    messagingSenderId: '117976496895',
    projectId: 'rebrand-6a7b0',
    authDomain: 'rebrand-6a7b0.firebaseapp.com',
    storageBucket: 'rebrand-6a7b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBncU18nCMx5V949EAa79LONugUX2_A_cE',
    appId: '1:117976496895:android:31f105558506a8a196aaca',
    messagingSenderId: '117976496895',
    projectId: 'rebrand-6a7b0',
    storageBucket: 'rebrand-6a7b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9BJhkpNai13lzYR3gh6AAfJVqVMjzLo',
    appId: '1:117976496895:ios:dd4422fbe18faae996aaca',
    messagingSenderId: '117976496895',
    projectId: 'rebrand-6a7b0',
    storageBucket: 'rebrand-6a7b0.appspot.com',
    iosBundleId: 'com.example.ap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACUc7ZO7-TlP-JPY-GmqUQmR3ZCkUOues',
    appId: '1:117976496895:web:cd0d629a9d8c9a7e96aaca',
    messagingSenderId: '117976496895',
    projectId: 'rebrand-6a7b0',
    authDomain: 'rebrand-6a7b0.firebaseapp.com',
    storageBucket: 'rebrand-6a7b0.appspot.com',
  );

}